[CmdletBinding()]
param([string]$Root = (Split-Path -Parent $PSScriptRoot))

$ErrorActionPreference = 'Stop'
$subjects = @(
    @('security/AI-Threat-Model.md','SEC-AITM','model inputs, retrieval context, tool calls, outputs, and operator overrides','AI gateway policy events and red-team findings','ranked abuse cases, mitigations, residual-risk decisions, and regression tests','untrusted content crossing into privileged tools or protected data','a prompt-injection or tool-confusion path produces an unauthorized action'),
    @('security/Artifact-Signing.md','SEC-SIGN','release artifact identity and provenance binding','immutable artifact digest, builder identity, and approved release metadata','verifiable signature, provenance attestation, and revocation status','the boundary between a build producer and every deployer or verifier','a signature verifies cryptographically but is bound to an untrusted builder or obsolete policy'),
    @('security/Container-Security.md','SEC-CONT','container image and runtime confinement controls','signed image, SBOM, runtime profile, workload identity, and resource policy','admission decision, runtime alerts, quarantine state, and investigation evidence','the image registry, cluster admission controller, node runtime, and workload namespace','a vulnerable or privileged container reaches execution despite admission policy'),
    @('security/Data-Loss-Prevention.md','SEC-DLP','classification-aware controls that prevent unauthorized disclosure','classified payload, actor purpose, destination, consent, and transfer context','allow, redact, quarantine, deny, or escalated-review decision with audit evidence','every egress path from protected storage, clients, AI context, logs, and federation','protected data leaves its permitted purpose, residency, audience, or retention boundary'),
    @('security/Fediverse-Security.md','SEC-FED','security controls for untrusted federated actors and instances','signed activities, remote instance posture, media, reports, and moderation signals','verified activity, rate decision, quarantine, block, or federation suspension record','the local ActivityPub server and every remote server, actor, object, and media origin','forged, replayed, abusive, or policy-incompatible activity affects a local user'),
    @('security/Incident-Response.md','SEC-IR','coordinated detection, containment, eradication, recovery, and learning','alert evidence, reporter context, affected assets, severity, and chain-of-custody record','incident timeline, containment actions, recovery decision, notifications, and corrective work','handoffs among automated detection, on-call responders, leadership, privacy, and legal authorities','containment is delayed, evidence is destroyed, or recovery reintroduces the cause'),
    @('security/KMS.md','SEC-KMS','cryptographic-key generation, custody, use, rotation, and destruction','authorized cryptographic operation, workload identity, key policy, and purpose','operation result plus immutable key-version and access evidence','applications request operations without receiving raw private key material','a compromised identity can export, reuse, or prevent rotation of protected key material'),
    @('security/Kubernetes-Security.md','SEC-K8S','cluster control-plane, admission, tenancy, and workload isolation','declarative workload, signed image, namespace policy, identity, and network intent','admission decision, scheduled confined workload, and policy-violation evidence','API server, admission chain, controllers, nodes, namespaces, and external control planes','a tenant escapes isolation or an unauthorized manifest changes cluster state'),
    @('security/Machine-Attestation.md','SEC-ATST','proof that a worker matches an approved hardware and software state','nonce, device identity, measured boot claims, firmware state, and verifier policy','fresh attestation verdict with evidence, expiry, and permitted trust tier','an untrusted campus or personal device requests admission to a compute trust tier','stale, cloned, unverifiable, or downgraded measurements are accepted'),
    @('security/Network-Segmentation.md','SEC-NET','default-deny network zones and explicitly authorized service paths','source identity, destination service, protocol, environment, and policy context','time-bounded allow decision or stable denial with flow evidence','user, management, workload, storage, federation, and campus-compute network zones','an implicit route permits lateral movement or bypasses an application authorization check'),
    @('security/Penetration-Testing-Standard.md','SEC-PENT','authorized adversarial testing and accountable remediation','written scope, test identities, safety limits, environment, and evidence-handling plan','validated finding, severity, reproduction evidence, owner, due date, and retest result','the approved test team interacts with systems without acquiring production authority','testing harms users, exceeds authorization, or closes findings without independent retest'),
    @('security/PKI.md','SEC-PKI','certificate trust anchors, issuance profiles, renewal, and revocation','authenticated subject, approved profile, public key, validity request, and issuer policy','certificate chain, transparency or inventory record, renewal state, and revocation status','issuers and registration authorities determine which identities relying parties trust','an expired, misissued, weak, or revoked certificate remains trusted'),
    @('security/Prompt-Injection-and-Agent-Security.md','SEC-AGENT','separation of untrusted instructions from authorized agent control','user intent, retrieved content, tool schema, policy context, and proposed action','bounded plan, confirmation request, tool decision, result, and tamper-evident trace','natural-language content crosses into tool invocation or privileged side effects','indirect instructions override system policy or cause an action outside user intent'),
    @('security/SBOM.md','SEC-SBOM','complete component inventory for every releasable artifact','resolved dependency graph, build materials, licenses, versions, and artifact digest','machine-readable CycloneDX or SPDX inventory bound to the release provenance','build tooling describes components that scanners, operators, and responders consume','the inventory omits vendored, generated, container-base, firmware, or transitive components'),
    @('security/Secrets-Management.md','SEC-SECR','secret issuance, retrieval, rotation, revocation, and exposure response','authenticated workload or operator identity, declared purpose, and secret policy','short-lived secret reference or operation result plus access evidence','callers obtain capability without storing durable credentials in source or images','a secret is logged, committed, over-scoped, unrotated, or usable after revocation'),
    @('security/Security-Architecture.md','SEC-ARCH','system-wide trust boundaries and composition of preventive, detective, and recovery controls','architecture inventory, data classifications, identities, dependencies, and threat models','control allocation, trust-boundary map, residual risks, and verification plan','local institutional authority composes with common services and untrusted federation','component controls pass individually while an end-to-end path bypasses them'),
    @('security/Supply-Chain-Security.md','SEC-SUP','integrity from source change through dependency resolution, build, release, and deployment','reviewed source, locked dependencies, hermetic build inputs, builder identity, and policy','signed artifact, SBOM, provenance, scan results, promotion decision, and revocation route','contributors and upstreams hand artifacts to builders, registries, and deployment controllers','a compromised dependency, maintainer, runner, or registry produces a trusted release'),
    @('security/Threat-Model.md','SEC-TM','repeatable identification and treatment of system threats','system context, assets, actors, trust boundaries, data flows, assumptions, and change set','abuse cases, ranked risks, selected controls, owners, evidence, and accepted residual risk','every transition where authority, data classification, or administrative ownership changes','a material architecture change ships without revisiting affected threats and assumptions'),
    @('security/VM-Security.md','SEC-VM','virtual-machine image integrity, hypervisor isolation, lifecycle, and tenant controls','signed image, boot policy, tenant identity, network intent, and resource assignment','attested instance, isolated runtime, lifecycle evidence, and secure disposal record','guest, hypervisor, host management, storage, and campus network trust zones','a stale image, guest escape, snapshot leak, or management-plane compromise crosses tenants'),
    @('security/Vulnerability-Management.md','SEC-VULN','continuous discovery, prioritization, remediation, exception, and verification','asset inventory, SBOM, advisory, exploitability, exposure, and business impact','triaged finding, owner, deadline, mitigation or patch, exception expiry, and retest evidence','scanners and advisories inform accountable service owners and release gates','known exploitable exposure remains deployed because ownership or exception expiry is unclear'),
    @('security/Zero-Trust-Architecture.md','SEC-ZTA','continuous, context-aware authorization without implicit network trust','strong identity, device and workload posture, requested resource, action, and context','least-privilege decision, session constraints, telemetry, and re-evaluation trigger','each access request crosses an explicit policy-enforcement point regardless of location','network presence, prior authentication, or federation membership becomes permanent trust'),
    @('identity/ABAC-and-Policy.md','ID-ABAC','attribute-based decisions and lifecycle of authorization policy','verified subject, resource, action, environment attributes, and policy version','allow or deny decision, obligations, reason code, and evaluation evidence','policy decision points remain separate from enforcement points and source systems','missing, stale, conflicting, or attacker-controlled attributes grant access'),
    @('identity/Delegated-Authorization.md','ID-DELEG','time-bounded delegation of a subset of a principal authority','delegator identity, delegate, permitted actions, resource scope, purpose, and expiry','verifiable delegation grant, use record, attenuation chain, and revocation state','a service acts for a user or organization without receiving unrestricted credentials','delegated authority can be amplified, transferred, replayed, or used after revocation'),
    @('identity/Device-Identity.md','ID-DEVICE','unique device enrollment, posture binding, renewal, and retirement','device-generated key, enrollment proof, owner, platform posture, and requested trust tier','device credential, trust state, expiry, revocation handle, and inventory record','human identity is distinct from the managed or personal device presenting it','cloned credentials or an unmanaged device inherits trusted-device authorization'),
    @('identity/Entra-ID-SSO.md','ID-ENTRA','optional Algonquin-compatible enterprise SSO adapter behind portable identity contracts','OIDC metadata, client registration, institution claims, consent, and login request','normalized Commons identity, session, assurance, and stable authentication errors','the proprietary upstream issuer is isolated from portable clients and service authorization','vendor-specific identifiers or claims leak into common contracts or become the only login path'),
    @('identity/Federated-Social-Identity.md','ID-FED','mapping between local institutional people and federated social actors','local account state, actor URI, domain proof, consent, visibility, and moderation status','controlled actor linkage, discovery representation, unlinking, and tombstone behavior','institutional authentication authority remains separate from ActivityPub actor identity','a remote actor, recycled identifier, or public profile is treated as institutional authentication'),
    @('identity/Identity-Architecture.md','ID-ARCH','end-to-end identity authority, assurance, provisioning, session, and revocation boundaries','institution issuer, person and workload lifecycle events, policy, and relying-party request','normalized identity claims, assurance context, authorization inputs, and audit trail','each institution remains its identity authority while common protocols enable interoperability','a common service becomes a hidden global identity provider or local revocation fails to propagate'),
    @('identity/Identity-Separation.md','ID-SEP','separation of person, role, device, workload, social actor, and service identities','principal identifier, identity kind, authority, affiliation, role, and requested operation','unambiguous subject context and policy decision without identity conflation','one human may hold multiple institutional and non-institutional personas and devices','an identifier from one namespace is accepted as authority in another namespace'),
    @('identity/OIDC-OAuth2.md','ID-OIDC','portable authentication and delegated API authorization profiles','authorization request with PKCE, issuer metadata, client policy, scopes, and user session','validated tokens or codes with bounded audience, lifetime, assurance, and stable errors','browser, native client, issuer, authorization server, resource server, and redirect boundary','token substitution, redirect abuse, code interception, mix-up, or audience confusion succeeds'),
    @('identity/RBAC.md','ID-RBAC','coarse-grained role assignment for understandable administrative authorization','verified principal, institution, role definition, assignment authority, and resource scope','effective roles, decision inputs, assignment history, and removal state','role administration remains distinct from service-specific permission enforcement','role accumulation or ambiguous inheritance grants authority beyond current duties'),
    @('identity/SCIM-Provisioning.md','ID-SCIM','standards-based account and group lifecycle synchronization','authenticated SCIM request, stable external identifier, attributes, version, and lifecycle state','idempotent user or group state, conflict result, audit event, and deprovision confirmation','institution systems of record drive downstream accounts without sharing their databases','out-of-order updates, identifier reuse, or failed deprovisioning leaves unauthorized access'),
    @('identity/Service-Accounts.md','ID-SVC','non-human service principal ownership, credential lifecycle, and authorization','declared service owner, purpose, workload, requested permissions, and expiry policy','unique service principal, short-lived credentials, usage evidence, and revocation route','automation is attributable without impersonating a person or sharing credentials','an orphaned, shared, interactive, or over-privileged service account persists'),
    @('identity/Session-and-Token-Management.md','ID-SESS','session creation, token validation, renewal, revocation, and logout propagation','authenticated principal, assurance, client, audience, device context, and policy','bounded session and tokens, rotation state, revocation signal, and audit evidence','browser or native client state crosses issuer, gateway, and resource-service boundaries','stolen, replayed, overlong, wrong-audience, or revoked tokens remain usable'),
    @('identity/Workload-Identity.md','ID-WORK','cryptographic identity for software workloads without embedded static secrets','attested workload, namespace, service account, environment, and requested audience','short-lived workload credential, trust chain, policy decision, and rotation evidence','scheduler and identity issuer bind runtime workload state to service authorization','a copied token, compromised node, or spoofed workload gains cross-service authority')
)

function Add-SubjectContract([string]$Path, [object[]]$Subject, [bool]$Institution) {
    $content = Get-Content -LiteralPath $Path -Raw
    if ($content -match '(?m)^## Subject-specific control contract$') { return }
    $binding = if ($Institution) {
        "The Algonquin deployment MUST bind these controls to Algonquin-owned identity, policy, evidence retention, and incident routes without weakening the common contract."
    } else {
        "Institution forks MUST bind these controls to local identity, policy, evidence retention, and incident routes without weakening the common contract."
    }
    $block = @"
## Subject-specific control contract

| Dimension | Required definition |
|---|---|
| Owned responsibility | $($Subject[2]) |
| Authoritative input | $($Subject[3]) |
| Authoritative output | $($Subject[4]) |
| Primary trust boundary | $($Subject[5]) |
| Unsafe failure to prevent | $($Subject[6]) |

- **$($Subject[1])-001:** The owner MUST implement the responsibility and preserve the input-to-output evidence chain shown above.
- **$($Subject[1])-002:** The enforcement point MUST fail closed when identity, policy version, integrity, freshness, or required context cannot be verified.
- **$($Subject[1])-003:** A release MUST include a positive conformance case, an unauthorized or malformed case, a dependency-loss case, and a regression case for the unsafe failure.
- **$($Subject[1])-004:** Exceptions MUST identify scope, compensating controls, approver, expiry, monitoring, and a removal plan; permanent undocumented bypasses are prohibited.

$binding

### Verification scenarios

1. Prove the authoritative input produces the declared output with the active policy version and attributable actor or workload.
2. Alter or omit one trust-bearing input and prove the request is denied with a stable reason while protected content is excluded from diagnostics.
3. Make the principal dependency unavailable and prove the component enters its documented fail-closed or bounded degraded mode.
4. Revoke or expire the authority and prove cached state, sessions, queued work, and replicas stop accepting it within the declared propagation objective.

"@
    $anchor = '## Decision traceability'
    if (-not $content.Contains($anchor)) { throw "Missing insertion anchor: $Path" }
    $content = $content.Replace($anchor, "$block`r`n$anchor")
    Set-Content -LiteralPath $Path -Value $content -Encoding utf8NoBOM
}

$common = Join-Path $Root 'common/psdc-architecture/docs'
$algonquin = Join-Path $Root 'institutions/algonquin/algonquin-architecture/docs'
foreach ($subject in $subjects) {
    Add-SubjectContract (Join-Path $common $subject[0]) $subject $false
    Add-SubjectContract (Join-Path $algonquin $subject[0]) $subject $true
}

Write-Output "Added subject-specific contracts to $($subjects.Count * 2) high-risk security and identity specifications."
